spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/iateit-test
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
      show_sql: true
      format_sql: true

logging:
  level:
    org.hibernate.SQL: debug